### ISSUE TITLE
Giving lane prediction even if a blank image is passed.

### ISSUE THREAD

**Issue by Maheshtaparia01** [lucastabelini/PolyLaneNet#18]
Hi
The model is predicting the lane even if the nothing is there (image with all pixel with 0 / 1 value) or if I give a cat image as input, I am getting 3-4  lanes on that.

**Comment by lucastabelini** [comment]
I see two reasons for that. One is that these kinds of images are very different from the ones in the training set, which means the output is nothing meaningful. The other is that all datasets used on the paper have at least one lane per image. If the model you used was trained on TuSimple, it will have a huge bias towards predicting 3+ lanes, since the vast majority of the images have this number of lanes.
